# -*- coding: utf-8 -*-
"""GUPSYGoogleResearchProject.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aOaBUsizz9Q-WII3D7Uwjl6LfZgzx3Ib

# GUPSY Methods


```
# Markdown
```
"""

patient = 'AfricanAmerican'

patient = 1

print(patient)

patient1 = 'LatinoAmerican'

patient1 = 2

print(patient1)

patient2 = 'AsianAmerican'

patient2 = 3

print(patient2)

patient3 = 'MideasternAmerican'

patient3 = 4

print(patient3)

patient4 = 'WhiteAmerican'

patient4 = 5

print(patient4)

patient5 = list()

patients = 5

patients == 1

patients > 1

patientslist = ['AfricanAmerican', 'LatinoAmerican', 'AsianAmerican', 'MideasternAmerican', 'WhiteAmerican']

AfricanAmerican = ['male', 'female']
for item in AfricanAmerican:
  print('Hello', item)

LatinoAmerican = ['male', 'female']
for item in LatinoAmerican:
   print('Hello', item)

AsianAmerican = ['male', 'female']
for item in AsianAmerican:
  print('Hello', item)

MideasternAmerican = ['male', 'female']
for item in MideasternAmerican:
  print('Hello', item)

WhiteAmerican = ['male', 'female']
for item in WhiteAmerican:
  print('Hello', item)